version: '3'

services:
  webpack:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: takacsmark/web-intro-exmpl:dev-1.0
    ports:
      - 8080:8080
    volumes:
      - ./src:/usr/src/app/src
      - ./img:/usr/src/app/img
    